### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by crypto-shifu** [omsfinance/oms#6]
Remove this code duplication and update line 93 to call the getAveragePrice function instead:

from: uint256 rate = SafeMath.div(sumPrice, length);
to: uint256 rate = getAveragePrice();
        
https://github.com/omsfinance/oms/blob/b2fbd8a9c657af6389bb2a856d8618d675b0f3f1/contracts/v6/OraclePrice.sol#L83-L91

**Comment by arvisingh098** [comment]
This is not duplicate data this method is an internal method and getAveragePrice method is view method to get average price.
